### ISSUE TITLE
lsftp | incorrect display when pressing alt + backspace

### ISSUE THREAD

**Issue by m4xx1m** [blacknon/lssh#98] opened 2022-07-13 06:26 UTC
if try to delete using alt + backspace then

![image](https://user-images.githubusercontent.com/59927482/178663249-68127343-fbf7-4582-93d0-3e5194a673c3.png)

https://user-images.githubusercontent.com/59927482/178664962-82de0262-f07a-4e3b-9af1-3316e0593b58.mp4

**Comment by blacknon** [comment] 2022-07-18 14:48
This problem seems to be caused by the library we are using not supporting key bindings by default.
I will add this as a possible key binding in the next version or later.

**Comment by blacknon** [comment] 2022-07-25 06:03
I thought it was merged, but it wasn't.

https://github.com/c-bata/go-prompt/pull/112

**Comment by blacknon** [comment] 2022-07-25 11:13
If this pull request is passed, it will be ready for use.

https://github.com/c-bata/go-prompt/pull/261

**Comment by blacknon** [comment] 2024-05-03 11:08
I forked go-prompt, fixed it, and now the issue functionality works, so I close this issue.

**Closed by blacknon** 2024-05-03 11:08 UTC
